M48
; DRILL file {KiCad (6.0.7)} date Fri Mar 31 20:18:16 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-31T20:18:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.8539Y-2.6301
X5.0449Y-2.6301
T2
X4.8421Y-2.5108
X5.0567Y-2.5108
T0
M30
